baseURL = "https://trevordmiller.com/"
languageCode = "en-us"
title = "trevordmiller"
theme = "etch"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "My writing about software development."
  copyright = "If you would like to get updates when I publish new content, you can subscribe to my email list by sending an email to 'trevordmiller+subscribe@groups.io' with the subject of 'subscribe'."
  highlight = true

[permalinks]
  posts = "/:title/"
