name: CD
on:
  push:
    branches:
      - master
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login
      run: cargo login ${{ secrets.CRATE_REGISTRY_PAT }}
    - name: Publish
      if: success()
      run: cargo publish
    - name: Install
      if: success()
      run: cargo install trevordmiller
    - name: Generate
      if: success()
      run: trevordmiller generate
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: trevordmiller/trevordmiller.github.io
        target_branch: master
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    - name: Audit
      if: success()
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: 'https://trevordmiller.com'
        configPath: './.github/audit/lighthouserc.json'
        temporaryPublicStorage: true
        runs: 3
