name: CD
on:
  push:
    branches:
      - master
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Generate
      run: cargo run --release -- generate
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: trevordmiller/trevordmiller.github.io
        target_branch: master
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
