on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 0 * * *"

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo run --release
        working-directory: ./website
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./website/build
          repo: trevordmiller/trevordmiller.github.io
          target_branch: master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Audit
        if: success()
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: "https://trevordmiller.com"
          configPath: "./.github/workflows/production-website.json"
          temporaryPublicStorage: true
          runs: 3
