name: Continuous Integration

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: docker://github/super-linter:v2.0.0

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./scripts/build
      - name: Audit
        if: success()
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: "./.github/configuration/audit-local.json"
          temporaryPublicStorage: true
      - name: Links
        if: success()
        uses: peter-evans/link-checker@v1
        id: links
        with:
          args: --document-root ./build --verbose --recursive *
      - name: Exit
        run: exit ${{ steps.links.outputs.exit_code }}
