name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install
        run: sudo snap install hugo
      - name: Build
        run: hugo
        working-directory: ./src/write
      - name: Configure
        run: echo "trevordmiller.com" > ./src/write/public/CNAME
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./src/write/public
          repo: trevordmiller/trevordmiller.github.io
          target_branch: master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
