name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: cargo run --release
        working-directory: ./write
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./write/build
          repo: trevordmiller/trevordmiller.github.io
          target_branch: master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
