name: Merge
on:
  push:
    branches:
      - master
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Check
      run: cargo check
    - name: Test
      run: cargo test
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Format
      run: cargo fmt -- --check
  executable:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      run: cargo login ${{ secrets.CRATE_REGISTRY_PAT }}
    - name: Publish
      if: success()
      run: cargo publish
  website:
    runs-on: ubuntu-latest
    needs: [verify, executable]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install
      run: cargo install trevordmiller
    - name: Generate
      if: success()
      run: trevordmiller generate
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: trevordmiller/trevordmiller.github.io
        target_branch: master
        build_dir: public
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
    - name: Audit
      if: success()
      uses: treosh/lighthouse-ci-action@v2
      with:
        urls: 'https://trevordmiller.com'
        configPath: './.github/audit/lighthouserc.json'
        temporaryPublicStorage: true
        runs: 3
