name: Schedule

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: E2E
        run: ./.github/scripts/e2e
      - name: Audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: "./.github/configuration/audit-production.json"
          temporaryPublicStorage: true
          runs: 3
          urls: |
            https://trevordmiller.com
            https://trevordmiller.com/cicd-reference/
            https://trevordmiller.com/about/
            https://trevordmiller.com/resume/
            https://trevordmiller.com/projects/
